# Generated by Django 5.2.7 on 2025-12-15 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryUni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название категории университета')),
            ],
            options={
                'verbose_name': 'Категорию университета',
                'verbose_name_plural': 'Категории университетов',
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название Факультета')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название Университета')),
                ('description', models.TextField(verbose_name='Описание')),
                ('requirements', models.TextField(verbose_name='Требование для поступление')),
                ('fee', models.CharField(max_length=50, verbose_name='Стоимость обучения')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Фото')),
                ('views', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('video_link', models.CharField(max_length=500, verbose_name='Видео')),
                ('address', models.CharField(max_length=250, verbose_name='Адрес')),
                ('website_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка для сайта институа')),
                ('education_language', models.CharField(max_length=100, verbose_name='Язык обучения')),
                ('category_uni', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyFutureUni.categoryuni', verbose_name='Название категории университета')),
                ('faculty', models.ManyToManyField(to='MyFutureUni.faculty', verbose_name='Факультет')),
            ],
            options={
                'verbose_name': 'Университет',
                'verbose_name_plural': 'Университеты',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название учебной программы')),
                ('description', models.TextField(verbose_name='Описания учебной программы')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFutureUni.university')),
            ],
            options={
                'verbose_name': 'Учебная программа',
                'verbose_name_plural': 'Учебные программы',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название учебной направление')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFutureUni.university')),
            ],
            options={
                'verbose_name': 'Учебная направления',
                'verbose_name_plural': 'Учебные направлении',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyFutureUni.university', verbose_name='Университет')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
