# Generated by Django 5.2.7 on 2025-12-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyFutureUni', '0002_profileuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='location',
        ),
    ]
