# Generated by Django 5.2.7 on 2025-12-19 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFutureUni', '0003_remove_profileuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='views',
            field=models.IntegerField(verbose_name='Просмотры'),
        ),
    ]
