# Generated by Django 5.2.7 on 2025-12-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyFutureUni', '0004_alter_university_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100, verbose_name='API посетителей')),
            ],
            options={
                'verbose_name': 'API посетителя',
                'verbose_name_plural': 'API посетителей',
            },
        ),
        migrations.RemoveField(
            model_name='university',
            name='views',
        ),
        migrations.AddField(
            model_name='university',
            name='views',
            field=models.ManyToManyField(blank=True, null=True, to='MyFutureUni.ip', verbose_name='Просмотры'),
        ),
    ]
